# EndreXY 2022-09-18: Based on Github Actions starter "Java with Gradle, By GitHub Actions"
#
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        javaversion: [8, 11, 17]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.javaversion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.javaversion }}
        distribution: 'temurin'

    - name: Build with Gradle, JDK ${{ matrix.javaversion }}
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build
        cache-disabled: true
